{% set name = "tidb-vector" %}
{% set version = "0.0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tidb_vector-{{ version }}.tar.gz
  sha256: dfd16b31b06f025737f5c7432a08e04265dde8a7c9c67d037e6e694c8125f6f5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0
    - numpy >=1,<3
  run_constrained:
    - SQLAlchemy >=1.4,<3

test:
  imports:
    - tidb_vector
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A Python client for TiDB Vector
  home: https://github.com/pingcap/tidb-vector-python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
