{% set name = "tidb-vector" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tidb_vector-{{ version }}.tar.gz
  sha256: cb4e2c88610b63729e0f779ccd599f4c1e77a308f0baefd0a4c69d47f7d2baa0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8.1,<4.0
    - numpy >=1.0.0,<2.0.0
  run_constrained:
    - SQLAlchemy >=1.4,<3

test:
  imports:
    - tidb_vector
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A Python client for TiDB Vector
  home: https://github.com/pingcap/tidb-vector-python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
